# Generated by Django 5.2.7 on 2026-04-27 17:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multa_por_dia', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('limite_dias_emprestimo', models.PositiveIntegerField(default=14, help_text='Número máximo de dias para um empréstimo padrão.')),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tombo', models.CharField(help_text='Código identificador único do exemplar físico', max_length=50, unique=True)),
                ('estado_conservacao', models.CharField(default='Bom', max_length=100)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('emprestado', 'Emprestado'), ('manutencao', 'Em Manutenção'), ('perdido', 'Perdido')], default='disponivel', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('celular', models.CharField(max_length=15, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(max_length=255)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('recebimento_alertas', models.CharField(choices=[('email', 'Email'), ('celular', 'Celular')], default='email', max_length=10)),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para bloquear temporariamente o leitor')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField(default=django.utils.timezone.now)),
                ('data_devolucao', models.DateField()),
                ('cadastrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_realizados', to=settings.AUTH_USER_MODEL)),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.exemplar')),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.leitor')),
            ],
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_devolucao_real', models.DateField(default=django.utils.timezone.now)),
                ('valor_multa', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('multa_paga', models.BooleanField(default=False)),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolucoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('emprestimo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.emprestimo')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('edicao', models.CharField(max_length=100)),
                ('idioma', models.CharField(default='Português', max_length=50)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('numero_paginas', models.IntegerField()),
                ('classificacao', models.IntegerField()),
                ('sinopse', models.TextField()),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='biblioteca_app.autor')),
                ('editora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='biblioteca_app.editora')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='biblioteca_app.genero')),
            ],
        ),
        migrations.AddField(
            model_name='exemplar',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplares', to='biblioteca_app.livro'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('funcao', models.CharField(choices=[('administrador', 'Administrador'), ('bibliotecario', 'Bibliotecário')], default='bibliotecario', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ativa', 'Ativa - Na Fila'), ('disponivel', 'Livro Disponível (Aguardando Retirada)'), ('atendida', 'Atendida (Empréstimo Realizado)'), ('cancelada', 'Cancelada')], default='ativa', max_length=20)),
                ('leitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='biblioteca_app.leitor')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='biblioteca_app.livro')),
            ],
        ),
    ]
