# Generated by Django 5.2.7 on 2026-04-28 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='livros_imagens/')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_adicionais', to='biblioteca_app.livro')),
            ],
        ),
    ]
