# Generated by Django 5.2.7 on 2026-04-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0002_imagemlivro'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitor',
            name='id_leitor',
            field=models.CharField(blank=True, help_text='ID Único ou Matrícula', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='localizacao',
            field=models.CharField(blank=True, help_text='Ex: Estante A, Prateleira 2', max_length=100, null=True),
        ),
    ]
