# Generated by Django 5.2.7 on 2026-04-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0003_leitor_id_leitor_livro_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_leitores/'),
        ),
    ]
