# Generated by Django 5.2.7 on 2026-04-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0004_leitor_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='dias_renovacao',
            field=models.PositiveIntegerField(default=7, help_text='Quantidade de dias adicionados na renovação.'),
        ),
    ]
