# Generated by Django 5.2.7 on 2026-04-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0006_perfilusuario_celular_perfilusuario_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_funcionarios/'),
        ),
    ]
